version: "3.9"

services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "80:80"
    depends_on:
      - mineral-catalog
  mineral-catalog:
    build: ~/Code/mineral-catalog
    ports:
      - "80:8001"
  pug-or-ugh:
    build: ~/Code/pug-or-ugh
    ports:
      - "80:8000"