version: "3.9"

services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - "8080:80"
    depends_on:
      - mineral-catalog
  mineral-catalog:
    build: ${CODE_DIR}/mineral-catalog
    ports:
      - "8081:80"